import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../controllers/article_controller.dart';
import '../models/article.dart';

class ArticleCreatePage extends StatelessWidget {
  final ArticleController controller = Get.find<ArticleController>();

  final _formKey = GlobalKey<FormState>();
  final titleController = TextEditingController();
  final authorController = TextEditingController();
  final categoryController = TextEditingController();
  final descriptionController = TextEditingController();
  final readTimeController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Create Article"),
      ),
      body: Padding(
        padding: EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              TextFormField(
                controller: titleController,
                decoration: InputDecoration(labelText: "Title"),
                validator: (value) => value!.isEmpty ? "Enter title" : null,
              ),
              TextFormField(
                controller: authorController,
                decoration: InputDecoration(labelText: "Author"),
                validator: (value) => value!.isEmpty ? "Enter author" : null,
              ),
              TextFormField(
                controller: categoryController,
                decoration: InputDecoration(labelText: "Category"),
                validator: (value) => value!.isEmpty ? "Enter category" : null,
              ),
              TextFormField(
                controller: descriptionController,
                decoration: InputDecoration(labelText: "Description"),
                validator: (value) =>
                    value!.isEmpty ? "Enter description" : null,
              ),
              TextFormField(
                controller: readTimeController,
                decoration:
                    InputDecoration(labelText: "Read Time (in minutes)"),
                keyboardType: TextInputType.number,
                validator: (value) => value!.isEmpty ? "Enter read time" : null,
              ),
              SizedBox(height: 20),
              ElevatedButton(
                child: Text("Create"),
                onPressed: () async {
                  if (_formKey.currentState!.validate()) {
                    final newArticle = Article(
                      id: "", // id will be generated by backend
                      title: titleController.text,
                      author: authorController.text,
                      category: categoryController.text,
                      description: descriptionController.text,
                      readTime: int.parse(readTimeController.text),
                      createdAt: DateTime.now(),
                      updatedAt: DateTime.now(),
                    );
                    try {
                      await controller.createArticle(newArticle);
                      Get.back();
                    } catch (e) {
                      Get.snackbar("Error", e.toString());
                    }
                  }
                },
              )
            ],
          ),
        ),
      ),
    );
  }
}
